set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Replace your existing terminal-overrides with:
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"
set -ag terminal-overrides ",*:Tc"
set -s escape-time 0

# split panes using | and -, make sure they open in the same path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

unbind r
bind r source-file ~/.tmux.conf

# Set scroll back limit
set-option -g history-limit 4000

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -r j select-pane -d
bind -r k select-pane -u
bind -r l select-pane -r
bind -r h select-pane -l

bind -r o new-window -c '#{pane_current_path}';

bind-key i run-shell "tmux neww $HOME/.dotfiles/scripts/cheat.sh"

bind-key f run-shell "tmux neww $HOME/.dotfiles/scripts/tmux-sessionizer"

bind-key b run-shell "$HOME/.dotfiles/scripts/wallpaper.sh > /dev/null"

bind-key v run-shell "tmux neww $HOME/.dotfiles/scripts/fivex-vpn.sh"

set -g mouse on
set-option -sg escape-time 10
set-option -g focus-events on

set-window-option -g mode-keys vi

bind e copy-mode
# Use "y" to copy to tmux buffer AND system clipboard (via pbcopy)
bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi w send-keys -X select-word

#tpm plugin
set -g @plugin 'tmux-plugins/tpm'

#list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-resurrect' # Save tmux sessions
set -g @plugin 'tmux-plugins/tmux-continuum' # Save every 15 minutes

# List of plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# Other plugins you might want
set -g @plugin 'tmux-plugins/tmux-yank'  # Better copy-paste integration

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# init TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

